language: dita
install:
  - echo "Installed"
script:
  - sh .travis/publish.sh
after_success:
  - sh .travis/deploy.sh
env:
  global:
    - ANT_OPTS=-Xmx1024M
before_install:
  - chmod +x .travis/publish.sh
  - chmod +x tools/oxygen-publishing-engine-3.x/bin/dita
  - chmod +x .travis/deploy.sh
    
    